Injector:
  IPLoggerEntry:
    class: IPLoggerEntry
  IPBanEntry:
    class: IPBanEntry
  IPLoggerService:
    class: IPLoggerService

SecurityAdmin:
  extensions:
    - IPLoggerSecurityAdminExtension
